### PR TITLE
ts: only read .json files when parsing IDLs

### LINKED ISSUE #1188: anchor test fails when IDL JSON file is open in Vim
Hi, I tried to follow the simple tutorial example.

```
anchor init mysolanaapp --javascript
anchor build
```

I opened `target/idl/mysolanaapp.json` to take a look, generating a temporary swap file `./target/idl/.mysolanaapp.json.swp`. This causes `anchor test` to fail.

```
-> % anchor test
...

warning package.json: No license field
$ /Users/x/code/mysolanaapp/node_modules/.bin/mocha -t 1000000 tests/


  mysolanaapp
    1) Is initialized!


  0 passing (3ms)
  1 failing

  1) mysolanaapp
       Is initialized!:
     SyntaxError: Unexpected token b in JSON at position 0
      at JSON.parse (<anonymous>)
      at /Users/x/code/mysolanaapp/node_modules/@project-serum/anchor/dist/cjs/workspace.js:66:34
      at Array.forEach (<anonymous>)
      at Object.get (node_modules/@project-serum/anchor/dist/cjs/workspace.js:63:39)
      at Context.<anonymous> (tests/mysolanaapp.js:10:38)
      at processImmediate (node:internal/timers:464:21)



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Only after much experimentation did I realize that **closing Vim or removing this swap file** would make it succeed. Not quite sure what's going on here, but certainly doesn't seem expected.

### PR DESCRIPTION
**Pull request by johnrees**
fixes #1188

I wasn't sure whether to add a try/catch here or not, in the end I kept it simple. This should exclude .swp files when parsing IDLs.

### CODE REVIEW

File: ts/src/workspace.ts [hunk 1]
```diff
@@ -47,19 +47,21 @@ const workspace = new Proxy({} as any, {
...
-        const name = camelCase(idl.name, { pascalCase: true });
-        if (idl.metadata && idl.metadata.address) {
-          workspaceCache[name] = new Program(
-            idl,
-            new PublicKey(idl.metadata.address)
-          );
-        }
-      });
+      fs.readdirSync(idlFolder)
+        .filter((file) => file.endsWith(".json"))
```
Comment (johnrees) [inline ts/src/workspace.ts:51]: `.filter((file) => file.endsWith(".json"))` is the only change here, everything else is whitespace
