### PR TITLE
avm: Handle empty .version file

### LINKED ISSUE #1405: avm: running avm list results in panic
```
➜  ~ avm list
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Could not parse version file: unexpected end of input while parsing major version number', avm/src/lib.rs:177:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
0.3.0%
```

### PR DESCRIPTION
**Pull request by tomlinton**
- Fix panic for `avm list` on empty `.version` file
- If you run `avm install <list>` and the `.version` file is empty, write the installed version to it

Closes https://github.com/project-serum/anchor/issues/1405

### CODE REVIEW

File: avm/src/lib.rs [hunk 1]
```diff
@@ -174,7 +179,7 @@ pub fn list_versions() -> Result<()> {
         if installed_versions.contains(v) {
             flags.push("installed");
         }
-        if current_version().unwrap() == v.clone() {
+        if current_version().is_ok() && current_version().unwrap() == v.clone() {
```
Comment (fanatid) [inline avm/src/lib.rs:182]:
```suggestion
        if matches!(current_version(), Ok(cv) if cv == *v) {
```
Version without `unwrap` :slightly_smiling_face:

Comment (armaniferrante) [reply avm/src/lib.rs:182]: very nice! :dancers:
