### PR TITLE
lang: Handle invalid camel case ident more gracefully

### LINKED ISSUE #4017: Unhandled Panic in Anchor Instruction Dispatch Code Generation
Executive Summary

The Anchor Framework's instruction dispatch code generator contains an unhandled error condition that causes a panic when processing instructions with names that cannot be converted to valid Rust token streams. 

This vulnerability exists in anchor-syn/src/codegen/program/dispatch.rs and can be triggered by crafting Anchor programs with malicious instruction names, causing build failures during macro expansion.

Vulnerable Code 

https://github.com/solana-foundation/anchor/blob/master/lang/syn/src/codegen/program/dispatch.rs

pub fn generate(program: &Program) -> proc_macro2::TokenStream {
    // Dispatch all global instructions.
    let global_ixs = program.ixs.iter().map(|ix| {
        let ix_method_name = &ix.raw_method.sig.ident;
        
        // VULNERABLE CODE - LINES 9-13 
        let ix_name_camel: proc_macro2::TokenStream = ix_method_name
            .to_string() // Convert identifier to string
            .to_camel_case() // Convert to CamelCase (e.g., "my_function" -> "MyFunction")
            .parse() // Parse string as TokenStream
            .expect("Failed to parse ix method name in camel as TokenStream");
            // ^^^^^^ PANICS if parsing fails!
        
        let discriminator = quote! { instruction::#ix_name_camel::DISCRIMINATOR };
        let ix_cfgs = &ix.cfgs;

        quote! {
            #(#ix_cfgs)*
            if data.starts_with(#discriminator) {
                return __private::__global::#ix_method_name(
                    program_id,
                    accounts,
                    &data[#discriminator.len()..],
                )
            }
        }
    });

}

Detailed Vulnerability Explanation

The Vulnerable Code Path

rustlet ix_name_camel: proc_macro2::TokenStream = ix_method_name
to_string() //

Step 1: Convert Ident to String
to_camel_case() //

Step 2: Convert to CamelCase
parse() //

Step 3: Parse as TokenStream - can FAIL
expect //

Step 4: PANIC if parse() returns Err

What each step does:

.to_string() - Converts instruction name identifier to String

Example: initialize → "initialize"
.to_camel_case() - Converts to CamelCase format

Example: "initialize" → "Initialize"
Example: "create_account" → CreateAccount"

.parse() - Attempts to parse string as TokenStream

Returns Result<TokenStream, LexError>

Can fail if the string is not valid Rust syntax

expect() - Unwraps the Result

Panics if parse() returned Err
Crashes the entire macro expansion

Why This Is Vulnerable

The code assumes that converting a function name to CamelCase will always produce a valid

However, this assumption is false in several cases:

Case 1: Reserved Keywords

pub mod my_program {
    pub fn r#type(ctx: Context<Initialize>) -> Result<()> {
        // "type" is a Rust keyword, prefixed with r#
        Ok(())
    }
}

// After to_camel_case(): "Type"
// After parse(): VALID (not a problem in this specific case)

Special Characters After Conversion

a malicious instruction name converts to invalid syntax
"my_fn_1" → "MyFn1" // Valid
"_leading" → "Leading" // Valid after trimming underscore
"123start" → "123Start" // INVALID - starts with digit!

Non-ASCII Characters

If somehow non-ASCII characters sneak through
"café" → "Café" // May or may not parse depending on characters
"函数" → "函数" // Invalid Rust identifier
Case 4: Empty or Edge Cases
rust"" → "" // Empty string cannot parse as TokenStream
"_" → "" // Single underscore might convert to empty
"__" → "" // Multiple underscores might convert to empty

Malicious Code Generation could craft problematic names

Most Realistic Attack:

A malicious or buggy procedural macro that generates Anchor instruction functions with names that become invalid after CamelCase conversion. 

Impact:

Developers blocked from using certain patterns

Framework limitation without workaround
Community frustration

Recommended Fix

Secure Implementation
rustuse crate::Program;
use heck::CamelCase;
use quote::quote;
use syn::parse_quote;

pub fn generate(program: &Program) -> proc_macro2::TokenStream {
    // Dispatch all global instructions.
    let global_ixs = program.ixs.iter().map(|ix| {
        let ix_method_name = &ix.raw_method.sig.ident;
        

 // FIXED: Proper error handling with helpful message
        let ix_name_camel_str = ix_method_name.to_string().to_camel_case();
        
        // Validate the converted name is a valid identifier
        let ix_name_camel: proc_macro2::TokenStream = match ix_name_camel_str.parse() {
            Ok(tokens) => tokens,
            Err(e) => {
                // Provide detailed error with context
                return syn::Error::new(
                    ix_method_name.span(),
                    format!(
                        "Failed to generate instruction dispatch for '{}': \
                         CamelCase conversion '{}' is not a valid Rust identifier. \
                         Error: {}. \
                         Hint: Avoid using raw identifiers (r#) or special characters in instruction names.",
                        ix_method_name,
                        ix_name_camel_str,
                        e
                    )
                ).to_compile_error();
            }
        };
        
        let discriminator = quote! { instruction::#ix_name_camel::DISCRIMINATOR };
        let ix_cfgs = &ix.cfgs;

        quote! {
            #(#ix_cfgs)*
            if data.starts_with(#discriminator) {
                return __private::__global::#ix_method_name(
                    program_id,
                    accounts,
                    &data[#discriminator.len()..],
                )
            }
        }
    });

    quote! {
        /// Performs method dispatch.
        ///
        /// Each instruction's discriminator is checked until the given instruction data starts with
        /// the current discriminator.
        ///
        /// If a match is found, the instruction handler is called using the given instruction data
        /// excluding the prepended discriminator bytes.
        ///
        /// If no match is found, the fallback function is executed if it exists, or an error is
        /// returned if it doesn't exist.
        fn dispatch<'info>(
            program_id: &Pubkey,
            accounts: &'info [AccountInfo<'info>],
            data: &[u8],
        ) -> anchor_lang::Result<()> {
            #(#global_ixs)*

            // ... rest of dispatch logic
        }
    }
}

Alternative Implementation: Pre-validation

rustuse crate::Program;
use heck::CamelCase;
use quote::quote;

pub fn generate(program: &Program) -> proc_macro2::TokenStream {
    // Dispatch all global instructions.
    let global_ixs = program.ixs.iter().map(|ix| {
        let ix_method_name = &ix.raw_method.sig.ident;
        let ix_name_str = ix_method_name.to_string();
        let ix_name_camel_str = ix_name_str.to_camel_case();
        
        // ALTERNATIVE FIX: Validate before parsing
        if !is_valid_rust_identifier(&ix_name_camel_str) {
            return syn::Error::new(
                ix_method_name.span(),
                format!(
                    "Instruction name '{}' converts to invalid identifier '{}' in CamelCase. \
                     Instruction names must be valid Rust identifiers that remain valid after CamelCase conversion.",
                    ix_name_str,
                    ix_name_camel_str
                )
            ).to_compile_error();
        }
        
        // Safe to parse now - we've validated it
        let ix_name_camel: proc_macro2::TokenStream = ix_name_camel_str
            .parse()
            .expect("Validated identifier should parse");
        
        let discriminator = quote! { instruction::#ix_name_camel::DISCRIMINATOR };
        let ix_cfgs = &ix.cfgs;

        quote! {
            #(#ix_cfgs)*
            if data.starts_with(#discriminator) {
                return __private::__global::#ix_method_name(
                    program_id,
                    accounts,
                    &data[#discriminator.len()..],
                )
            }
        }
    });

    // ... rest of function
}

/// Validate that a string is a valid Rust identifier
fn is_valid_rust_identifier(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    
    let mut chars = s.chars();
    let first = chars.next().unwrap();
    
    // First character must be alphabetic or underscore
    if !first.is_alphabetic() && first != '_' {
        return false;
    }
    
    // Remaining characters must be alphanumeric or underscore
    if !chars.all(|c| c.is_alphanumeric() || c == '_') {
        return false;
    }
    
    // Check if it's a reserved keyword
    if is_rust_keyword(s) {
        return false;
    }
    
    true
}

/// Check if string is a Rust keyword
fn is_rust_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "break" | "const" | "continue" | "crate" | "else" | "enum" |
        "extern" | "false" | "fn" | "for" | "if" | "impl" | "in" | "let" |
        "loop" | "match" | "mod" | "move" | "mut" | "pub" | "ref" | "return" |
        "self" | "Self" | "static" | "struct" | "super" | "trait" | "true" |
        "type" | "unsafe" | "use" | "where" | "while" | "async" | "await" | "dyn" |
        "abstract" | "become" | "box" | "do" | "final" | "macro" | "override" |
        "priv" | "typeof" | "unsized" | "virtual" | "yield" | "try"
    )
}

### PR DESCRIPTION
**Pull request by jamie-osec**
Closes #4017

`Ident::new` panics on invalid identifiers; `syn::parse_str` is the recommended alternative for untrusted input.

### CODE REVIEW

**Review by 0x4ka5h — CHANGES_REQUESTED** [review]
can we also use the error propagation here? which is currently just `unwrap()`
https://github.com/jamie-osec/anchor/blob/bf495ac3df5483a80c37b51ad534ee8fb47821bc/lang/syn/src/codegen/program/common.rs#L45

File: lang/syn/src/codegen/program/cpi.rs [hunk 1]
```diff
@@ -13,12 +13,21 @@ pub fn generate(program: &Program) -> proc_macro2::TokenStream {
...
+                        return quote! { compile_error!(concat!("error generating ix variant: `", #err, "`")) };
+                    }
+                };
                 let method_name = &ix.ident;
                 let args: Vec<&syn::PatType> = ix.args.iter().map(|arg| &arg.raw_arg).collect();
-                let discriminator = {
-                    let name = generate_ix_variant_name(&name_str);
-                    quote! { <instruction::#name as anchor_lang::Discriminator>::DISCRIMINATOR }
+                let discriminator = match generate_ix_variant_name(&name_str) {
+                    Ok(name) => quote! { <instruction::#name as anchor_lang::Discriminator>::DISCRIMINATOR },
```
Comment (akash-osec) [inline lang/syn/src/codegen/program/cpi.rs:26]:
```
error: expected one of `,` or `>`, found keyword `as`
  --> programs/cashiers-check/src/lib.rs:12:1
   |
12 | #[program]
   | ^^^^^^^^^^ expected one of `,` or `>`
   |
   = note: this error originates in the attribute macro `program` (in Nightly builds, run with -Z macro-backtrace for more info)
help: expressions must be enclosed in braces to be used as const generic arguments
   |
12 | { #[program] }
   | +            +

error[E0433]: failed to resolve: could not find `DISCRIMINATOR` in `instruction`
  --> programs/cashiers-check/src/lib.rs:12:1
   |
12 | #[program]
   | ^^^^^^^^^^
   | |
   | could not find `DISCRIMINATOR` in `instruction`
   | help: a trait with a similar name exists: `Discriminator`
   |
   = note: this error originates in the attribute macro `program` (in Nightly builds, run with -Z macro-backtrace for more info)

```
is it from there?

**Review by Otter-0x4ka5h — CHANGES_REQUESTED** [review]
Do you know what causes these error and results in failing tests?

File: lang/syn/src/codegen/program/cpi.rs (hunk 1 above)
Comment (jamie-osec) [reply lang/syn/src/codegen/program/cpi.rs]: Copy-paste error, fixed

**Review by Otter-0x4ka5h — APPROVED** [review]
lgtm

**Review by jacobcreech — APPROVED** [review]
