### PR TITLE
Handle arrays with const as size in instruction data

### LINKED ISSUE #1623: lang: const array size not supported in instruction data
the following mwe
```
use anchor_lang::prelude::*;

declare_id!("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS");

const MAX_SIZE: usize = 5;

#[program]
pub mod tst {
    use super::*;

    pub fn initialize(_ctx: Context<Initialize>, _data: [u8; MAX_SIZE]) -> Result<()> {
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize {}
```

throws
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', lang/syn/src/idl/mod.rs:202:76                                       
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

related to #968 and #1485

### PR DESCRIPTION
**Pull request by skrrb**
Closes #1623

### CODE REVIEW

**Comment by paul-schaaf** [comment]
is this ready for review?

**Comment by skrrb** [comment]
yes, I hope I haven't left anything out

File: lang/syn/src/idl/file.rs [hunk 1]
```diff
@@ -159,7 +159,9 @@ pub fn parse(
                 .map(|arg| {
                     let mut tts = proc_macro2::TokenStream::new();
```
Comment (paul-schaaf) [inline lang/syn/src/idl/file.rs:160]: you can adjust the `to_idl_type` function so it accepts a `syn::Type` instead of a `syn::Field` and then you can use it here

Comment (skrrb) [reply lang/syn/src/idl/file.rs]: 👍

**Comment by paul-schaaf** [comment]
Thank you!
