### PR TITLE
fix: enfore type & count matching between ix handler and #instruction[(..)] args

### LINKED ISSUE #3897: Instruction Parameters in `#[instruction(..)]` Not Enforced at Compile-Time
- Instruction parameters defined in the `#[instruction(..)]` attribute are not enforced as actual instruction arguments. The compiler currently allows functions to omit these parameters, silently compiling without error.
- Example [solpg.io](https://beta.solpg.io/68af203fcffcf4b13384d88a)

### LINKED ISSUE #3997: Anchor does not enforce strict type checking between instruction args and #[instruction(...)] attribute
While implementing and testing for [#3897](), it was observed that Anchor does not strictly enforce matching argument types between instruction definitions and their corresponding #[instruction(...)] attributes.

Example:
```

pub fn abcd(
    ctx: Context<ABCD>,
    data: u64,
) -> Result<()> {
    Ok(())
}

#[derive(Accounts)]
#[instruction(data: u8)]
pub struct ABCD<'info> {
    pub user: Signer<'info>,
}
```

In this example, data is defined as u64 in the instruction but as u8 in the #[instruction(...)] attribute.

The code compiles successfully without errors.

At runtime, it behaves inconsistently:

When passing a small value (within u8 range), it executes fine.

When passing a large value, it results in a runtime RangeError:

RangeError: The value of "value" is out of range. It must be >= 0 and <= 255. Received 256

Expected behavior:
Type mismatches between instruction arguments and #[instruction(...)] declarations should be caught at compile time.

Impact:
Potential for unexpected runtime errors or inconsistent behavior (possible DoS if misused).

Proposed action:
Add stricter compile-time validation to ensure instruction argument types match the #[instruction(...)] signature.

### PR DESCRIPTION
**Pull request by Otter-0x4ka5h**
this pr enforces and fixes types on args.
Example: 1
```rs 
// fail
pub fn abcd(
    ctx: Context<ABCD>,
    data: u64,
) -> Result<()> {
    Ok(())
}

#[derive(Accounts)]
#[instruction(data: u8)]
pub struct ABCD<'info> {
    pub user: Signer<'info>,
}
```

Example: 2
```rs
// pass
type myType = u64;
pub fn abcd(
    ctx: Context<ABCD>,
    data: u64,
) -> Result<()> {
    Ok(())
}

#[derive(Accounts)]
#[instruction(data: myType)]
pub struct ABCD<'info> {
    pub user: Signer<'info>,
}

```

Example: 3
```rs 
// fail
pub fn abcd(
    ctx: Context<ABCD>,
    data: u64,
) -> Result<()> {
    Ok(())
}

#[derive(Accounts)]
#[instruction(data: u64, ehe: u64)]
pub struct ABCD<'info> {
    pub user: Signer<'info>,
}
```

Example: 4
```rs 
// pass
pub fn abcd(
    ctx: Context<ABCD>,
    data: u64,
) -> Result<()> {
    Ok(())
}

#[derive(Accounts)]
#[instruction(data: u64)]
pub struct ABCD<'info> {
    pub user: Signer<'info>,
}
```
Closes #3997 
Closes #3897

### CODE REVIEW

**Review by jamie-osec — APPROVED** [review]

**Comment by jamie-osec** [comment]
Also closes #453

File: lang/syn/src/codegen/program/handlers.rs [hunk 1]
```diff
@@ -113,6 +113,57 @@ pub fn generate(program: &Program) -> proc_macro2::TokenStream {
...
+                    let method_name = syn::Ident::new(
+                        &format!("__anchor_validate_ix_arg_type_{}", idx),
+                        proc_macro2::Span::call_site(),
+                    );
+                    quote! {
+                        // Type validation for argument #idx
+                        if #anchor::__ANCHOR_IX_PARAM_COUNT > #idx {
+                            if false {
+                                // This code is never executed but is type-checked at compile time
+                                let __type_check_arg: #arg_ty = panic!();
```
Comment (jamie-osec) [inline lang/syn/src/codegen/program/handlers.rs:145]: What kind of error does this produce for the user when the argument is mismatched? Adding a `#[allow(unreachable_code)]` to this block could be helpful to silence a confusing warning that I think will appear

Comment (0x4ka5h) [reply lang/syn/src/codegen/program/handlers.rs:145]: yeah, we can add that derivative and silence unreachable warnings.
also, the current code produce this error
```
error[E0277]: the trait bound `u64: IsSameType<u8>` is not satisfied
  --> programs/test-instruction-validation/src/lib.rs:7:1
   |
7  | #[program]
   | ^^^^^^^^^^ the trait `IsSameType<u8>` is not implemented for `u64`
   |
note: required by a bound in `TypeMismatch::<'info>::__anchor_validate_ix_arg_type_0`
```

Comment (jamie-osec) [reply lang/syn/src/codegen/program/handlers.rs:145]: Can you try [`diagnostic::on_unimplemented`](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-diagnosticon_unimplemented-attribute) to improve the diagnostics here?
```rs
#[diagnostic::on_unimplemented(
  message = "`{Self}` is not the same type as `{T}`",
  note = "ensure `#[instruction(..)]` argument types match those of the instruction handler"
)]
```
or something similar should produce nice diagnostics

**Comment by jamie-osec** [comment]
LGTM now

**Review by jacobcreech — APPROVED** [review]
