### PR TITLE
client: Fix websocket url parsing

### LINKED ISSUE #574: client: Websocket urls for custom clusters are not parsed correctly
As shown here, https://github.com/project-serum/anchor/blob/master/client/src/cluster.rs#L119, the protocol specifies `http://`, when it should be `ws://`. Similar for `https://`.

### PR DESCRIPTION
**Pull request by gabesamu**
Should close #574 
Used set_scheme() from url package to change websocket url from http:// to ws://.

### CODE REVIEW

File: client/src/cluster.rs [hunk 1]
```diff
@@ -116,7 +118,7 @@ mod tests {
         let url = "http://my-url.com:7000/";
```
Comment (armaniferrante) [inline client/src/cluster.rs:118]: Can we add an additional test using TLS. Given  `https://my-url.com:7000/"`, then `"wss://my-url.com:7001/"` should be used.

Comment (0xlucius) [reply client/src/cluster.rs:118]: Yeah, will do that real quick.

Comment (0xlucius) [reply client/src/cluster.rs:124]: Added https testing for both port and no_port, just like the http tests, and added an if block to change to wss or ws based on what scheme url is already using.
