### PR TITLE
fix: Update `proc-macro2` usage for latest nightly

### LINKED ISSUE #3662: error[E0599]: no method named `source_file` found for struct `proc_macro2::Span` in the current scope
I kept getting this error ... idk why . 

mac silicon
[rust 1.86](https://github.com/solana-foundation/anchor/issues/3661)
avm 0.31.0

i tried all different installs

error[E0599]: no method named `source_file` found for struct `proc_macro2::Span` in the current scope
   --> /Users/stevensanborn/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-syn-0.31.0/src/idl/defined.rs:499:66
    |
499 | ...n::call_site().source_file().path();
    |                   ^^^^^^^^^^^ method not found in `Span`

so what fixed it for em was

line 499  ... let source_path = proc_macro2::Span::call_site().file();

### PR DESCRIPTION
**Pull request by cryptopapi997**
As of nightly-2025-04-16, `SourceFile` and the methods around it [don't exist anymore](https://github.com/rust-lang/rust/pull/139671), so anyone updating rust or installing rust won't be able to compile the idl anymore. `proc-macro2` [already updated](https://github.com/dtolnay/proc-macro2/pull/497), this PR updates anchor accordingly. Note that this will require users to update to the latest nightly (and will break users with an older nightly). Idk if this counts as a breaking change since it only affects nightly...

Fixes https://github.com/solana-foundation/anchor/issues/3662

### CODE REVIEW

File: lang/syn/src/idl/defined.rs [hunk 1]
```diff
@@ -496,7 +496,7 @@ pub fn gen_idl_type(
                 use crate::parser::context::CrateContext;
                 use quote::ToTokens;
 
-                let source_path = proc_macro2::Span::call_site().source_file().path();
+                let source_path = proc_macro2::Span::call_site().file();
```
Comment (niooss-ledger) [inline lang/syn/src/idl/defined.rs:499]: The documentation in https://github.com/dtolnay/proc-macro2/blob/24bbf16d9df01d5f7d9ac39bdfbaea85f4c194fb/src/lib.rs#L467-L478 states for `.file`:

> This might not correspond to a valid file system path. It might be remapped, or might be an artificial path such as `"<macro expansion>"`.

Shouldn't `.local_file()` be used instead?

Comment (cryptopapi997) [reply lang/syn/src/idl/defined.rs:499]: my mistake, good catch! fixed!

**Comment by kingmanas** [comment]
Replace the respective error line with 
#### 📁 File:
`defined.rs`

#### 📝  Line 499:
```rust
let source_path = proc_macro2::Span::call_site().file();

**Comment by Rayato159** [comment]
I'm facing this problem too even though I use stable version of rustc.

**Comment by RealAyyo** [comment]
+

File: lang/syn/src/idl/defined.rs [hunk 2]
```diff
@@ -496,79 +496,90 @@ pub fn gen_idl_type(
...
-                            if let syn::PathArguments::AngleBracketed(args) = &segment.arguments {
-                                let inners = args
-                                    .args
-                                    .iter()
-                                    .map(|arg| match arg {
-                                        syn::GenericArgument::Type(ty) => match ty {
-                                            syn::Type::Path(inner_ty) => {
-                                                inner_ty.path.to_token_stream().to_string()
+                if let Some(source_path) = proc_macro2::Span::call_site().local_file() {
+                    if let Ok(Ok(ctx)) = find_path("lib.rs", &source_path).map(CrateContext::parse)
```
Comment (acheroncrypto) [inline lang/syn/src/idl/defined.rs:500]: Nit: The new indentation makes the changes seem bigger than they actually are (+82 −70). It would be great if you could rewrite these lines to use only one indentation.

**Review by acheroncrypto — COMMENTED** [review]
Thanks for the quick fix.

We're also planning to make the IDL generation use the stable compiler by default and make code that required `nightly` optional via a CLI flag to avoid issues like this one. It sounds like these methods will be stabilized (as mentioned in https://github.com/rust-lang/rust/pull/139671), so we might be able to avoid `nightly` completely when that happens.

Related: There is an open issue (https://github.com/rust-lang/rust/issues/139903) regarding the naming of `local_file`.

**Comment by hryer** [comment]
Is anything that I can help maybe?, I need this fix ASAP. Also, I want to tell the CI failed 

```
no method named `source_file` found for struct `proc_macro2::Span` in the current scope
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-syn-0.31.0/src/idl/defined.rs:499:66
    |
499 |                 let source_path = proc_macro2::Span::call_site().source_file().path();
    |                                                                  ^^^^^^^^^^^ method not found in `Span`

```

**Comment by jacobcreech** [comment]
@hryer we're waiting on the update and I'll check into the CI

**Comment by andreisilviudragnea** [comment]
Hello. Is this going to be released as a hotfix for Anchor v0.31.0?

**Comment by quanghuynguyen1902** [comment]
Please fix it ASAP.

**Comment by moribus-single** [comment]
having the same issue
even in the new empty anchor project

**Comment by conceitodigital** [comment]
Facing the same issue.

**Comment by romeoscript** [comment]
> ```rust
> source_path
> ```

i can't find this file , where would i locate it ?

**Comment by iamramtin** [comment]
Using `anchor build --no-idl` works as a temporary workaround (tested on Anchor v0.30.1)

**Comment by romeoscript** [comment]
> Using `anchor build --no-idl` works as a temporary workaround (tested on Anchor v0.30.1)

so how do i generate IDL for frontend use ?

**Comment by cryptopapi997** [comment]
You can follow my workaround from here for both program & idl: https://github.com/solana-foundation/anchor/issues/3662#issuecomment-2809237122

File: lang/syn/src/idl/defined.rs [hunk 3]
```diff
@@ -496,7 +496,11 @@ pub fn gen_idl_type(
                 use crate::parser::context::CrateContext;
                 use quote::ToTokens;
 
-                let source_path = proc_macro2::Span::call_site().source_file().path();
+                let source_path = match proc_macro2::Span::call_site().local_file() {
+                    Some(source_path) => source_path,
+                    None => return Err(anyhow!("No source path found")),
```
Comment (acheroncrypto) [inline lang/syn/src/idl/defined.rs:501]: I think returning error here could cause undesired behavior because we always want [the rest of the code](https://github.com/solana-foundation/anchor/blob/649b9d6c5ef19d8e15ea35888f0b1a846cd03b48/lang/syn/src/idl/defined.rs#L577-L615) to run.

The old method didn't return an optional path, so it's probably unlikely for the new `local_file` method to return `None` in real world usage, but it's better to be safe than sorry here.

Comment (cryptopapi997) [reply lang/syn/src/idl/defined.rs:501]: I see. I'm not quite sure how you'd want me to avoid indenting [the stuff that's conditional on the path existing](https://github.com/solana-foundation/anchor/blob/649b9d6c5ef19d8e15ea35888f0b1a846cd03b48/lang/syn/src/idl/defined.rs#L500-L574) in that case :sweat_smile: . Do you have a suggestion? Feel free to push to the branch yourself if that's simpler.

Comment (cryptopapi997) [reply lang/syn/src/idl/defined.rs:501]: gotcha - will change it to an empty path instead

File: lang/syn/src/idl/defined.rs [hunk 4]
```diff
@@ -496,7 +496,9 @@ pub fn gen_idl_type(
                 use crate::parser::context::CrateContext;
                 use quote::ToTokens;
 
-                let source_path = proc_macro2::Span::call_site().source_file().path();
+                // If no path was found, just return an empty path and let the find_path function handle it
+                let source_path = proc_macro2::Span::call_site().local_file().unwrap_or(std::path::PathBuf::new());
+
```
Comment (acheroncrypto) [inline lang/syn/src/idl/defined.rs:501]: Format error in CI: https://github.com/solana-foundation/anchor/actions/runs/14524829367/job/40754178701?pr=3663#step:7:1

Can also use `unwrap_or_default` here:

```suggestion
                let source_path = proc_macro2::Span::call_site()
                    .local_file()
                    .unwrap_or_default();
```

Comment (cryptopapi997) [reply lang/syn/src/idl/defined.rs]: I felt like this way is more explicit to us setting it to the empty path in the case where it's None, but in the 2v1 I'll concur

File: lang/syn/src/idl/defined.rs [hunk 5]
```diff
@@ -496,12 +496,9 @@ pub fn gen_idl_type(
...
                 use quote::ToTokens;
 
-                let source_path = match proc_macro2::Span::call_site().local_file() {
-                    Some(source_path) => source_path,
-                    // If no path was found, just return an empty path and let the find_path function handle it
-                    None => std::path::PathBuf::new(),
-                };
-
+                // If no path was found, just return an empty path and let the find_path function handle it
+                let source_path = proc_macro2::Span::call_site().local_file().unwrap_or(std::path::PathBuf::new());
```
[the remark this answers is not in the document]
Comment (cryptopapi997) [reply lang/syn/src/idl/defined.rs]: https://github.com/solana-foundation/anchor/pull/3663#discussion_r2049662159

File: lang/syn/src/idl/defined.rs (hunk 4 above)
Comment (acheroncrypto) [reply lang/syn/src/idl/defined.rs]: All good. I don't really mind it but `clippy` usually complains about it with [`clippy::unwrap_or_default`](https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_or_default).

**Review by acheroncrypto — APPROVED** [review]
We're most likely going to make a patch release for this issue. Thanks for the fix and also responsiveness!

**Comment by adama789** [comment]
Hi, how to pull these changes? Will it be released in anchor 0.31.1?

**Comment by Vinayapr23** [comment]
How will these changes be reflected? In anchor 0.31.1 
So what to do with current 0.31.0 in the meantime

**Comment by stevensanborn** [comment]
anchor-cli 0.31.0
rustc 1.88.0-nightly (191df20fc 2025-04-18)
adding to cargo toml worked for me :
 proc-macro2 = { version = "1.0.95"}

**Comment by h0lme3** [comment]
Is it fixed?

**Comment by 0xJamesBong** [comment]
So what's the solution?

**Comment by Vinayapr23** [comment]
> So what's the solution?

Update to anchor 0.31.1 which was released today

**Comment by h0lme3** [comment]
> > So what's the solution?
> 
> Update to anchor 0.31.1 which was released today

please check the issue, I figured out the issue yesterday but today I am facing a new issue
https://github.com/solana-foundation/anchor/issues/3676#issuecomment-2817299670

**Comment by 0xm4ud** [comment]
@hryer this line: let source_path = proc_macro2::Span::call_site().source_file().path();
into this: let source_path = proc_macro2::Span::call_site().file().to_string();

**Comment by cryptopapi997** [comment]
For anyone still runing into this issue:

Make sure you're using
- anchor v0.31.1
- latest rust nightly 
- proc_macro2 v0.1.95 in your cargo.lock

**Comment by rotcan** [comment]
Getting below error while using 

- anchor v0.31.1
- rust nightly-2025-04-21
- proc_macro2 v0.1.95 

**Error**

no method named `file` found for reference `&proc_macro::Span` in the current scope
    |
465 |             Span::Compiler(s) => s.file(),
    |                                    ^^^^ method not found in `&Span`

error[E0599]: no method named `local_file` found for reference `&proc_macro::Span` in the current scope
    |
473 |             Span::Compiler(s) => s.local_file(),
    |                                    ^^^^^^^^^^ method not found in `&Span`

**Comment by 0xm4ud** [comment]
> Getting below error while using
> 
> * anchor v0.31.1
> * rust nightly-2025-04-21
> * proc_macro2 v0.1.95
> 
> **Error**
> 
> no method named `file` found for reference `&proc_macro::Span` in the current scope | 465 | Span::Compiler(s) => s.file(), | ^^^^ method not found in `&Span`
> 
> error[E0599]: no method named `local_file` found for reference `&proc_macro::Span` in the current scope | 473 | Span::Compiler(s) => s.local_file(), | ^^^^^^^^^^ method not found in `&Span`

have you tried reverting proc_macro2 v0.1.95 to proc_macro2 v0.1.94?

**Comment by rotcan** [comment]
Hi @0xm4ud ,



> @rotcan
> 
> > Getting below error while using
> > 
> > * anchor v0.31.1
> > * rust nightly-2025-04-21
> > * proc_macro2 v0.1.95
> > 
> > **Error**
> > no method named `file` found for reference `&proc_macro::Span` in the current scope | 465 | Span::Compiler(s) => s.file(), | ^^^^ method not found in `&Span`
> > error[E0599]: no method named `local_file` found for reference `&proc_macro::Span` in the current scope | 473 | Span::Compiler(s) => s.local_file(), | ^^^^^^^^^^ method not found in `&Span`
> 
> have you tried reverting proc_macro2 v0.1.95 to proc_macro2 v0.1.94?

With below configuration

- anchor v0.31.1
- rust nightly - 2025-04-21
- proc_macro2 v0.1.94
- solana - 2.1.4

I am getting this error

no method named `file` found for struct `proc_macro2::Span` in the current scope
   --> /.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-syn-0.31.1/src/idl/defined.rs:501:22
    |
500 |                   let source_path = proc_macro2::Span::call_site()
    |  ___________________________________-
501 | |                     .file()
    | |                     -^^^^ method not found in `Span`
    | |_____________________|
    |

**Comment by 0xm4ud** [comment]
I saw that error this morning. What I did was: cargo update -p proc-macro2, rustup override set 1.81, which solved it for me.

**Comment by rotcan** [comment]
@0xm4ud , still getting same error with below setting :(

- anchor 0.31.1
- rust- 1.81
- proc_macro2 v0.1.94
- solana - 2.1.4

no method named `file` found for struct `proc_macro2::Span` in the current scope
   --> /.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anchor-syn-0.31.1/src/idl/defined.rs:501:22
    |
500 |                   let source_path = proc_macro2::Span::call_site()
    |  ___________________________________-
501 | |                     .file()
    | |                     -^^^^ method not found in `Span`
    | |_____________________|

**Comment by 0xm4ud** [comment]
@rotcan hmm.. cargo update -p proc-macro2 should've changed/updated your proc-macro2 version, but by your post I see still is 1.94, try removing the lib /proc-macro2-1.0.94/ diectory and running cargo update -p proc-macro2 again.

Updating proc-macro2 v1.0.94 -> v1.0.95

**Comment by rotcan** [comment]
@0xm4ud Got it working thanks. I deleted proc-macro2-1.0.94 & 95 directory and anchor-syn-0.31.1 directory in cargo registry. Then ran rustup update. 
Following config worked
rustup - 2025-04-21 nightly
anchor - 0.31.1
solana - 2.14.0
proc-macro2 - 1.0.95

**Review by Dustin4444 — COMMENTED** [review]
#3952
