### PR TITLE
fix: write anchor expand output to stdout

### LINKED ISSUE #4267: anchor expand must dump to stdout
Subj. We can pipe it into file when needed.

### PR DESCRIPTION
**Pull request by Nicknamess96**
\`anchor expand\` saves the macro-expanded source to a timestamped file
under \`.anchor/expanded-macros/\` and prints the path, which makes it
impossible to pipe the output into other tools.

This patch writes the expanded source directly to stdout so callers can
redirect it (\`> file.rs\`) or pipe it through formatters and pagers like
any other CLI tool.

The now-unused \`chrono\` dependency is also removed.

Closes #4267

### CODE REVIEW

File: cli/src/lib.rs
Comment (jamie-osec) [inline cli/src/lib.rs]: We can just pipe stderr straight to our own stdout
```suggestion
        .stdout(std::process::Stdio::null())
        .stderr(std::io::stdout())
        .status()
```

**Review by jamie-osec — APPROVED** [review]

File: CHANGELOG.md [hunk 1]
```diff
@@ -12,6 +12,8 @@ The minor version will be incremented upon a breaking change and the patch versi
 
 ### Features
 
+- cli: Write `anchor expand` output to stdout instead of a file ([#4269](https://github.com/solana-foundation/anchor/pull/4269)).
+
```
Comment (acheroncrypto) [inline CHANGELOG.md:16]: This is a breaking change.
