### PR TITLE
fix missing filename in 'Unable to read keypair file' errors

### LINKED ISSUE #2884: feature suggestion: 'Unable to read keypair file' should include name of keypair file it cannot read
Very minor but based on experience in class where people hadn't previously set up the Solana tools:

```
Error: Unable to read keypair file
```

is difficult for people that aren't aware of what they default keypair file used by the Solana CLI is (or that Anchor uses the same keypair file as the Solana CLI). It would be preferable if the error looked similar to:

```
Error: Unable to read keypair file (/home/user/.config/solana/id.json)
```

specifying whatever the file name in question is.

### PR DESCRIPTION
**Pull request by mikemaccana**
Fixes #2884

### CODE REVIEW

File: cli/src/lib.rs [hunk 1]
```diff
@@ -490,6 +490,12 @@ pub enum ClusterCommand {
     List,
 }
 
+fn get_keypair(path: String) -> Result<Keypair> {
+    let keypair = solana_sdk::signature::read_keypair_file(&path)
+        .map_err(|_| anyhow!("Unable to read keypair file ({})", path))?;
+    Ok(keypair)
```
Comment (acheroncrypto) [inline cli/src/lib.rs:496]: Not too important:

```suggestion
    solana_sdk::signature::read_keypair_file(&path)
        .map_err(|_| anyhow!("Unable to read keypair file ({path})"))
```

File: cli/src/lib.rs [hunk 2]
```diff
@@ -3707,8 +3709,7 @@ fn create_idl_account(
 ) -> Result<Pubkey> {
     // Misc.
     let idl_address = IdlAccount::address(program_id);
-    let keypair = solana_sdk::signature::read_keypair_file(keypair_path)
-        .map_err(|_| anyhow!("Unable to read keypair file"))?;
+    let keypair = get_keypair(cfg.provider.wallet.to_string())?;
```
Comment (acheroncrypto) [inline cli/src/lib.rs:3712]: This should use `keypair_path` instead:

```suggestion
    let keypair = get_keypair(keypair_path)?;
```

File: cli/src/lib.rs [hunk 3]
```diff
@@ -3789,8 +3790,7 @@ fn create_idl_buffer(
     idl: &Idl,
     priority_fee: Option<u64>,
 ) -> Result<Pubkey> {
-    let keypair = solana_sdk::signature::read_keypair_file(keypair_path)
-        .map_err(|_| anyhow!("Unable to read keypair file"))?;
+    let keypair = get_keypair(cfg.provider.wallet.to_string())?;
```
Comment (acheroncrypto) [inline cli/src/lib.rs:3793]: Same here, this should use `keypair_path` instead:

```suggestion
    let keypair = get_keypair(keypair_path)?;
```

**Review by acheroncrypto — CHANGES_REQUESTED** [review]
Thanks for the PR!

This currently is missing some parts, please search for `read_keypair_file` in your editor and fix all of them. Just to give an example:

https://github.com/coral-xyz/anchor/blob/0b9540cb84ce9340106b0b120c28463914864e07/cli/src/lib.rs#L3620-L3622

is not handled in this PR.

**Comment by mikemaccana** [comment]
Thanks. I did try and make get_keypair() take a path instead originally but read_keypair_file() really wants the trait `AsRef<std::path::Path>` and `WalletPath` doesn't implement it. I ended up converting to a string in this most recent update, is there a better way?

> `read_keypair_file` in your editor and fix all of them

Missed one. Got it now.

File: cli/src/lib.rs (hunk 2 above)
Comment (acheroncrypto) [reply cli/src/lib.rs:3706]: This doesn't seem resolved. I'm not suggesting to provide `WalletPath` type here, `keypair_path` is `&str`. If you change the `path` parameter type of `get_keypair` function to `&str`, it should work.

File: cli/src/lib.rs (hunk 3 above)
Comment (acheroncrypto) [reply cli/src/lib.rs:3787]: Same here.

**Review by acheroncrypto — CHANGES_REQUESTED** [review]
> Thanks. I did try and make get_keypair() take a path instead originally but read_keypair_file() really wants the trait `AsRef<std::path::Path>` and `WalletPath` doesn't implement it. I ended up converting to a string in this most recent update, is there a better way?

Taking in `&str` would be better than `String`.

> > `read_keypair_file` in your editor and fix all of them
> 
> Missed that one (originally I skipped it when playing with WalletPath as it wants a string). Got it now.

Thanks, there are 2 more though:

- https://github.com/coral-xyz/anchor/blob/499e1e67c6f4b248fc2349a70cdcfe57cf780cb7/cli/src/config.rs#L1268-L1269
- https://github.com/coral-xyz/anchor/blob/499e1e67c6f4b248fc2349a70cdcfe57cf780cb7/cli/src/config.rs#L534-L535

File: cli/src/lib.rs (hunk 2 above)
Comment (mikemaccana) [reply cli/src/lib.rs]: Yep, I wanted to chat to you about how to proceed.  Got it re: `&str`, done! Added a changelog too.

File: CHANGELOG.md [hunk 4]
```diff
@@ -22,6 +22,10 @@ The minor version will be incremented upon a breaking change and the patch versi
 
 ### Breaking
 
+## Next release
+
+- cli: add filename to 'Unable to read keypair file' errors. ([#2932](https://github.com/coral-xyz/anchor/pull/2932))
+
```
Comment (acheroncrypto) [inline CHANGELOG.md:28]: Please follow the existing template similar to https://github.com/coral-xyz/anchor/pull/2929/commits/0acc8aaae2f70e6884df511b12d46ad18dab6d89.

File: cli/src/config.rs [hunk 5]
```diff
@@ -531,7 +531,7 @@ impl Config {
     }
 
     pub fn wallet_kp(&self) -> Result<Keypair> {
-        solana_sdk::signature::read_keypair_file(&self.provider.wallet.to_string())
+        get_keypair(&self.provider.wallet.to_string())
```
Comment (acheroncrypto) [inline cli/src/config.rs:534]: Error message is still the same here. Need to remove the `map_err` line below.

File: cli/src/config.rs [hunk 6]
```diff
@@ -531,7 +531,7 @@ impl Config {
...
             .map_err(|_| anyhow!("Unable to read keypair file"))
```
Comment (acheroncrypto) [inline cli/src/config.rs:535]:
```suggestion
```

File: cli/src/lib.rs [hunk 7]
```diff
@@ -3707,8 +3703,7 @@ fn create_idl_account(
 ) -> Result<Pubkey> {
     // Misc.
     let idl_address = IdlAccount::address(program_id);
-    let keypair = solana_sdk::signature::read_keypair_file(keypair_path)
-        .map_err(|_| anyhow!("Unable to read keypair file"))?;
+    let keypair = get_keypair(&cfg.provider.wallet.to_string())?;
```
Comment (acheroncrypto) [inline cli/src/lib.rs:3706]: This keeps getting resolved, but it's not. It should either use the `keypair_path` parameter (rather than getting the configured wallet path from `cfg.provider.wallet`), or the `keypair_path` parameter should be removed.

File: cli/src/lib.rs [hunk 8]
```diff
@@ -3789,8 +3784,7 @@ fn create_idl_buffer(
     idl: &Idl,
     priority_fee: Option<u64>,
 ) -> Result<Pubkey> {
-    let keypair = solana_sdk::signature::read_keypair_file(keypair_path)
-        .map_err(|_| anyhow!("Unable to read keypair file"))?;
+    let keypair = get_keypair(&cfg.provider.wallet.to_string())?;
```
Comment (acheroncrypto) [inline cli/src/lib.rs:3787]: Same here.

**Review by acheroncrypto — CHANGES_REQUESTED** [review]

File: CHANGELOG.md (hunk 4 above)
Comment (mikemaccana) [reply CHANGELOG.md:28]: I did look at the existing entry, I just missed the `## [Unreleased]` heading.

File: cli/src/config.rs (hunk 5 above)
Comment (mikemaccana) [reply cli/src/config.rs:534]: Ugh obviously 🤦🏼‍♂️ - thanks for your patience.

File: cli/src/lib.rs (hunk 7 above)
Comment (mikemaccana) [reply cli/src/lib.rs:3706]: Got it, sorry I didn't realize `keypair_path` was dead code until now.

**Comment by mikemaccana** [comment]
`cargo clippy` bits fixed too.

**Review by acheroncrypto — APPROVED** [review]
Thank you!
